### ISSUE TITLE
Conflicting licensing information, GPLv2 vs GPLv3

### ISSUE THREAD

**Issue by tootea** [SanderBorgmans/OGRe#1]
It is currently not clear how this project is licensed. The LICENSE file contains the GNU GPL version 2 while the README.md says "OGRe is distributed as open source software under the conditions of the GPL license version 3" (and mentions a nonexistent COPYING file). The source files do not seem to carry copyright headers and the accompanying paper does not seem to say anything about licensing either.

It would be great if you could fix this inconsistency to make it clear to potential users what the licensing terms are. If the project is supposed to be under GPLv2, it would be best to clarify whether this means v2-only or v2+ (version 2 or later).

**Comment by SanderBorgmans** [comment]
Hi @tootea, thank you for bringing this to my attention. The LICENSE file was added a long time ago, and the README file was not written in accordance with this LICENSE, which was an ovesight on my part. I apologise for the inconvenience. I have updated both the README and LICENSE files to reflect the current permissions.
